# Generated by Django 4.1.7 on 2023-05-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_additionalimageitem_item_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название валюты')),
                ('conversion_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Коэффициент конвертации')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(default='RUB', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='temporary_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
