# Generated by Django 4.1.5 on 2023-02-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_account_about_yourself'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='about_yourself',
            field=models.TextField(null=True, verbose_name='О себе'),
        ),
    ]
