# Generated by Django 4.1.7 on 2023-05-29 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_currency_user_currency_user_temporary_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkinOrdersAndItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.item', verbose_name='Товар')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Связь заказов с товарами',
                'verbose_name_plural': 'Связи заказов с товарами',
            },
        ),
    ]
