# Generated by Django 4.1.7 on 2023-06-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_linkinordersanditems_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_code',
            field=models.TextField(default=1, verbose_name='Ключ оплаты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='temporary_currency',
            field=models.CharField(blank=True, default='RUB', max_length=3),
        ),
    ]
